apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dono directories ko as resources include karein
resources:
  - kubernetes/model-deploy.yaml
  - kubernetes/model-svc.yaml
  - kubernetes/streamlit-deploy.yaml
  - kubernetes/streamlit-svc.yaml
  - monitoring/servicemonitor.yaml
  - monitoring/fastapi-scaledobject.yaml