apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-deploy.yaml
  - model-svc.yaml
  - streamlit-deploy.yaml
  - streamlit-svc.yaml
  - fastapi-scaledobject.yaml

images:
  - name: mehmoodhaq7/house-price-model
    newTag: latest
  - name: mehmoodhaq7/streamlit
    newTag: latest